In [1]:
import pandas as pd
from src.utils.paths import PROCESSED_DATA_DIR

In [2]:
df = pd.read_csv(PROCESSED_DATA_DIR / "listings_clean.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2643 entries, 0 to 2642
Data columns (total 80 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   host_response_time                            2269 non-null   float64
 1   host_response_rate                            2269 non-null   float64
 2   host_acceptance_rate                          2188 non-null   float64
 3   host_is_superhost                             2643 non-null   bool
 4   host_listings_count                           2643 non-null   int64
 5   host_total_listings_count                     2643 non-null   int64
 6   host_has_profile_pic                          2643 non-null   bool
 7   host_identity_verified                        2643 non-null   bool
 8   neighbourhood_cleansed                        2643 non-null   str
 9   neighbourhood_group_cleansed                  2643 non-null   str
 10  latitude                                      2643 non-null   float64
 11  longitude                                     2643 non-null   float64
 12  property_type                                 2643 non-null   str
 13  room_type                                     2643 non-null   str
 14  accommodates                                  2643 non-null   int64
 15  bathrooms                                     2641 non-null   float64
 16  bedrooms                                      2632 non-null   float64
 17  beds                                          2620 non-null   float64
 18  price                                         2643 non-null   float64
 19  minimum_nights                                2643 non-null   int64
 20  maximum_nights                                2643 non-null   int64
 21  minimum_minimum_nights                        2643 non-null   float64
 22  maximum_minimum_nights                        2643 non-null   float64
 23  minimum_maximum_nights                        2643 non-null   float64
 24  maximum_maximum_nights                        2643 non-null   float64
 25  minimum_nights_avg_ntm                        2643 non-null   float64
 26  maximum_nights_avg_ntm                        2643 non-null   float64
 27  has_availability                              2643 non-null   bool
 28  availability_30                               2643 non-null   int64
 29  availability_60                               2643 non-null   int64
 30  availability_90                               2643 non-null   int64
 31  availability_365                              2643 non-null   int64
 32  number_of_reviews                             2643 non-null   int64
 33  number_of_reviews_ltm                         2643 non-null   int64
 34  number_of_reviews_l30d                        2643 non-null   int64
 35  availability_eoy                              2643 non-null   int64
 36  number_of_reviews_ly                          2643 non-null   int64
 37  first_review                                  1359 non-null   str
 38  last_review                                   1359 non-null   str
 39  review_scores_rating                          1359 non-null   float64
 40  review_scores_accuracy                        1359 non-null   float64
 41  review_scores_cleanliness                     1359 non-null   float64
 42  review_scores_checkin                         1359 non-null   float64
 43  review_scores_communication                   1359 non-null   float64
 44  review_scores_location                        1358 non-null   float64
 45  review_scores_value                           1358 non-null   float64
 46  instant_bookable                              2643 non-null   bool
 47  calculated_host_listings_count                2643 non-null   int64
 48  calculated_host_listings_count_entire_homes   2643 non-null   int64
 49  calculated_host_listings_count_private_rooms  2643 non-null   int64
 50  calculated_host_listings_count_shared_rooms   2643 non-null   int64
 51  reviews_per_month                             1359 non-null   float64
 52  host_tenure_years                             2643 non-null   float64
 53  log_number_of_reviews                         2643 non-null   float64
 54  has_reviews                                   2643 non-null   int64
 55  log_reviews_per_month                         2643 non-null   float64
 56  days_since_last_review                        1359 non-null   float64
 57  has_recent_review                             2643 non-null   int64
 58  availability_ratio_30                         2643 non-null   float64
 59  availability_ratio_60                         2643 non-null   float64
 60  availability_ratio_90                         2643 non-null   float64
 61  availability_ratio_365                        2643 non-null   float64
 62  high_availability                             2643 non-null   int64
 63  low_availability                              2643 non-null   int64
 64  beds_per_guest                                2620 non-null   float64
 65  bedrooms_per_guest                            2632 non-null   float64
 66  bathrooms_per_guest                           2641 non-null   float64
 67  is_entire_home                                2643 non-null   int64
 68  is_private_room                               2643 non-null   int64
 69  is_shared_room                                2643 non-null   int64
 70  property_type_apartment                       2643 non-null   int64
 71  property_type_condo                           2643 non-null   int64
 72  property_type_hotel                           2643 non-null   int64
 73  property_type_house                           2643 non-null   int64
 74  property_type_other                           2643 non-null   int64
 75  property_type_serviced_apartment              2643 non-null   int64
 76  neighbourhood_density                         2643 non-null   float64
 77  distance_to_nearest_rail                      2643 non-null   float64
 78  distance_to_CBD                               2643 non-null   float64
 79  distance_to_changi                            2643 non-null   float64
dtypes: bool(5), float64(38), int64(31), str(6)
memory usage: 1.5 MB

In [4]:
df[["neighbourhood_density", "distance_to_nearest_rail", "distance_to_CBD", "distance_to_changi"]].describe()

,neighbourhood_density,distance_to_nearest_rail,distance_to_CBD,distance_to_changi
count,2643.000000,2643.000000,2643.000000,2643.000000
mean,67.420025,0.481579,4.818903,17.981157
std,86.731136,0.398017,4.189769,4.660809
min,0.014346,0.007090,0.085665,2.321181
25%,7.531895,0.260909,1.919982,16.087542
50%,18.597811,0.421079,3.279334,18.446714
75%,97.118036,0.560891,6.566980,19.238851
max,252.216245,5.447640,19.493970,33.663387

In [5]:
df[["neighbourhood_density", "distance_to_nearest_rail", "distance_to_CBD", "distance_to_changi"]].isna().sum()

neighbourhood_density       0
distance_to_nearest_rail    0
distance_to_CBD             0
distance_to_changi          0
dtype: int64

In [6]:
{
    "neighbourhood_density",
    "distance_to_nearest_rail",
    "distance_to_CBD",
    "distance_to_changi",
}.issubset(df.columns)

True

In [7]:
{"host_since"}.issubset(df.columns)

False

In [8]:
df[["days_since_last_review", "availability_ratio_30", "availability_ratio_60", "availability_90", "availability_ratio_365", "high_availability", "low_availability", "beds_per_guest", "bathrooms_per_guest", "is_entire_home",
    "is_private_room", "is_shared_room", "property_type_apartment", "property_type_condo", "property_type_hotel", "property_type_house", "property_type_other","property_type_serviced_apartment"]].describe()

,days_since_last_review,availability_ratio_30,availability_ratio_60,availability_90,availability_ratio_365,high_availability,low_availability,beds_per_guest,bathrooms_per_guest,is_entire_home,is_private_room,is_shared_room,property_type_apartment,property_type_condo,property_type_hotel,property_type_house,property_type_other,property_type_serviced_apartment
count,1359.000000,2643.000000,2643.000000,2643.000000,2643.000000,2643.000000,2643.000000,2620.000000,2641.000000,2643.000000,2643.000000,2643.000000,2643.000000,2643.000000,2643.000000,2643.000000,2643.000000,2643.000000
mean,931.149375,0.716194,0.783661,73.486568,0.831374,0.854711,0.012486,0.690492,0.763272,0.491109,0.473326,0.018918,0.374574,0.096481,0.118426,0.091184,0.036701,0.282633
std,968.029524,0.330230,0.315188,26.390722,0.250369,0.352459,0.111061,0.698187,0.854642,0.500016,0.499382,0.136261,0.484104,0.295306,0.323173,0.287925,0.188062,0.450365
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,68.500000,0.633333,0.783333,75.000000,0.736986,1.000000,0.000000,0.500000,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,525.000000,0.866667,0.916667,85.000000,0.978082,1.000000,0.000000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1764.000000,0.966667,0.983333,89.000000,0.994521,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,3765.000000,1.000000,1.000000,90.000000,1.000000,1.000000,1.000000,22.000000,13.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
df[["days_since_last_review", "availability_ratio_30", "availability_ratio_60", "availability_90", "availability_ratio_365", "high_availability", "low_availability", "beds_per_guest", "bathrooms_per_guest", "is_entire_home",
    "is_private_room", "is_shared_room", "property_type_apartment", "property_type_condo", "property_type_hotel", "property_type_house", "property_type_other","property_type_serviced_apartment"]].isna().sum()

days_since_last_review              1284
availability_ratio_30                  0
availability_ratio_60                  0
availability_90                        0
availability_ratio_365                 0
high_availability                      0
low_availability                       0
beds_per_guest                        23
bathrooms_per_guest                    2
is_entire_home                         0
is_private_room                        0
is_shared_room                         0
property_type_apartment                0
property_type_condo                    0
property_type_hotel                    0
property_type_house                    0
property_type_other                    0
property_type_serviced_apartment       0
dtype: int64